sudo: false
dist: trusty

cache:
  apt: true
  ccache: true

git:
  depth: false

addons:
  apt:
    packages:
      - python3-pip
      - latexmk
      - libalgorithm-diff-perl
      - texlive
      - texlive-latex-extra
      - texlive-humanities
      - texlive-generic-recommended
      - graphviz
      - texlive-generic-extra


language: python
python:
  - "3.6"
install:
 - "pip3 install -r requirements.txt"
 - "pip3 install -r doc/requirements.txt"
script:
  - python3 op-test --help
  - python3 op-test --bmc-type AMI --run testcases.HelloWorld
  - (cd doc/; make latexpdf html)
  - ./ci/build-qemu-powernv.sh
  - wget https://openpower.xyz/job/openpower/job/openpower-op-build/label=slave,target=palmetto/lastSuccessfulBuild/artifact/images/palmetto.pnor
  - PATH=$(pwd)/qemu:$PATH ./op-test --bmc-type qemu --qemu-binary `pwd`/qemu/ppc64-softmmu/qemu-system-ppc64 --host-pnor palmetto.pnor --run-suite qemu

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local_dir: "doc/_build/html"
  on:
    branch: master
